### ISSUE TITLE
关于子页面

### ISSUE THREAD

**Issue by zzsnn** [HCLonely/hexo-theme-webstack#11]
![SharedScreenshot](https://user-images.githubusercontent.com/62317652/124153641-3788ee80-dac7-11eb-8e1b-5576c22eebba.jpg)
为何子页面试这样的，在/child/index.md中添加type:'child'显示错误，去除就显示上图

**Comment by HCLonely** [comment]
看一下你子页面的格式是否正确
https://raw.githubusercontent.com/HCLonely/hexo-theme-webstack/gh-pages/source/child/index.md
