### ISSUE TITLE
本地图片图标只显示一个

### ISSUE THREAD

**Issue by yeyu01** [HCLonely/hexo-theme-webstack#13]
![image](https://user-images.githubusercontent.com/78530990/137614146-441d5b83-0015-4a8a-89c7-24a79057ab71.png)
直接复制的主题，显示的这样
然后改了post_asset_folder: true，本地图片的插件也安了，请问是哪里还没有设置

**Comment by HCLonely** [comment]
链接发一下

**Comment by yeyu01** [comment]
https://aall.top/web/

**Comment by yeyu01** [comment]
好了感谢
