### ISSUE TITLE
每行显示个数问题

### ISSUE THREAD

**Issue by Pandolar** [HCLonely/hexo-theme-webstack#18]
您好, 想请问一下, 现在有支持自定义每行显示网站的个数吗, 现在貌似只能每行4个, 个人感觉每行显示的可以再多一点

**Comment by HCLonely** [comment]
![](https://s2.loli.net/2022/02/06/75qHnx8ozFiTfMr.png)
`<style>@media (min-width: 768px){.col-sm-3 {width: 20%;}}</style>`
直接使用自定义样式就行，20%那里，想要一行多少就改为`100/每行数量`%

**Comment by Pandolar** [comment]
非常感谢, 打扰大佬了~

**Comment by tlxkl** [comment]
配置网站用的第二种方法  为什么链接前的图片显示不出来

**Comment by HCLonely** [comment]
> 配置网站用的第二种方法 为什么链接前的图片显示不出来

第二种是哪种？
