### ISSUE TITLE
页脚版权问题

### ISSUE THREAD

**Issue by yansheng836** [HCLonely/hexo-theme-webstack#2]
页脚中的版权，好像都是`webstack`，是不可修改的，能否考虑改成主题`_config.yml`中的`author`、或者新增一个字段来配置？
（ps：我特地去看了下WebStackPage的开源协议，是MIT，修改后好像问题不大。）

![image](https://user-images.githubusercontent.com/45334066/87876622-e09c1d80-ca0b-11ea-80b8-cff333f91936.png)

**Comment by HCLonely** [comment]
你想要什么效果，只自定义你圈出来的这部分吗，还是自定义页脚

**Comment by yansheng836** [comment]
我觉得超链接可以不用改，直接该这么版权所有者即可。
比如`autuor: 小明`，显示`© 2020 小明 design by Viggo | Power by Hexo & hexo-theme-webstack`。

**Comment by yansheng836** [comment]
example：

https://www.volf.club/
![image](https://user-images.githubusercontent.com/45334066/87877295-0c210700-ca10-11ea-961b-188ade6e1e5c.png)

https://5nav.ml/
![image](https://user-images.githubusercontent.com/45334066/87877249-cebc7980-ca0f-11ea-8251-01b5fd7b6e9c.png)

**Comment by HCLonely** [comment]
- 这样
![image](https://user-images.githubusercontent.com/26346802/87891477-a31bac80-ca6c-11ea-8d68-ef9d1f57d678.png)
- 还是这样
![image](https://user-images.githubusercontent.com/26346802/87891751-9fd4f080-ca6d-11ea-8648-fd05588ce5e0.png)

**Comment by yansheng836** [comment]
第二个

**Comment by huangapple** [comment]
备案号怎么加？
