### ISSUE TITLE
网站图片路径问题

### ISSUE THREAD

**Issue by sandianyiyuan** [HCLonely/hexo-theme-webstack#3]
使用gitlab 的page服务部署，网站在子目录下，网站的不能正确显示路径是为什么呢？css js那些文件都能正常加载。  
需要在配置文件图片路径中加上项名才行，是我哪里没配对么

**Comment by HCLonely** [comment]
子目录的话确实会这样，最近没时间，寒假会解决这个问题

**Comment by sandianyiyuan** [comment]
今天我试着改了一下，改来改去好像也没改啥，图标正常了....

**Comment by sandianyiyuan** [comment]
> 今天我试着改了一下，改来改去好像也没改啥，图标正常了....

对比发现，配置文件中图片路径去掉前面的斜杠，网站部署在子目录中可以正常显示图片  
`img: images/logos/github.png`
