### ISSUE TITLE
如何取消页面滚动

### ISSUE THREAD

**Issue by zhouyaxiong** [HCLonely/hexo-theme-webstack#30]
您好，再使用这个hexo-theme-webstack导航项目过程中，遇到以下问题

问题描述:点击到左侧的标签分类之后，右侧的页面会有滚动的效果，观感不太好，

我想问下如何关闭这个滚动的功能

**Comment by HCLonely** [comment]
`source/js/footer.js`44行`duration: 500, `改为`duration: 0, `
https://github.com/HCLonely/hexo-theme-webstack/blob/2c0659650696d14deb3496816b5cfb9606c85578/source/js/footer.js#L44
