### ISSUE TITLE
我的关于本站页面需要我自己用 markdown 去写，而非在配置文件中硬编码去写，会出问题的

### ISSUE THREAD

**Issue by Lavaver** [HCLonely/hexo-theme-webstack#31]

**Comment by Lavaver** [comment]
而且正常的 markdown 页面该显示什么样就显示什么样，不要到最后一片空白只有排版错误的页脚，这个博客框架稍微准确点没有markdown就没有灵魂，不要以为是 webstack 就砍了markdown兼容，基本的md兼容必须要有

**Comment by Lavaver** [comment]
如果你不信的话你可以[亲自下载使用 hexo 主题库中任何主题](https://hexo.io/themes)，它们在有各自特色功能时也完全或绝大部分兼容md，更准确点你的 webstack 主题本质上也是博客主题的一种，更不该砍掉 md 兼容

**Comment by HCLonely** [comment]
[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
