### ISSUE TITLE
主题配置中左上角flag的图标问题和custom选项中的body问题

### ISSUE THREAD

**Issue by slske** [HCLonely/hexo-theme-webstack#5]
您好，有两个小问题说一下，
1.
  flag:
    icon: flag-cn  
    name: Chinese
icon这个图标路径是默认的images\flags目录，但我是将这个导航主题嵌套到我另一个博客里面的，所以这个路径我就没法用。

2.主题配置中custom配置里的body选项，
pc模式是在最左下角，且链接失效
![QQ截图20210213150049](https://user-images.githubusercontent.com/48957981/107844192-50408280-6e0c-11eb-8e5e-3d3e85ceef79.jpg)
在手机模式会错位。
![image](https://user-images.githubusercontent.com/48957981/107843832-410c0580-6e09-11eb-823c-e7da8ef5bbd0.png)

这是我填写的配置：
``` 
custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
    <a href="https://beian.miit.gov.cn"><img src="/dchh/images/yumkbwan.png"><span>蜀ICP备20005665号-1</span></a>|<a href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral"><img src="/dchh/images/又拍云_logo5.png" height="20" width="40" ></a>
```

**Comment by HCLonely** [comment]
第一个问题暂时无法修复，第二个这样显示正常，你需要添加css样式来定位
