### ISSUE TITLE
图标丢失

### ISSUE THREAD

**Issue by youthlql** [HCLonely/hexo-theme-webstack#8]
![image](https://user-images.githubusercontent.com/49017153/112605680-8719a780-8e52-11eb-981e-9ceeb660cacc.png)
如上图所示，图标丢失

下图是我的配置
![image](https://user-images.githubusercontent.com/49017153/112605733-96005a00-8e52-11eb-8bae-b8a78c952a51.png)
![image](https://user-images.githubusercontent.com/49017153/112605773-9f89c200-8e52-11eb-99f6-c68249d9e1f6.png)

我知道是路径问题但是我不知道怎么改

我的地址: https://youthlql.gitee.io/lql_nav/

**Comment by youthlql** [comment]
在线等，随时回复

**Comment by youthlql** [comment]
![image](https://user-images.githubusercontent.com/49017153/112606285-276fcc00-8e53-11eb-8599-51d16bc95132.png)
这里是这样显示的，少了个lql_nav

**Comment by HCLonely** [comment]
暂时不支持子页面

**Comment by youthlql** [comment]
期待你的更新~
